config/routes.rb
Rails.application.routes.draw do
  get 'meals/new'

  devise_for :users

  resources :orders do
    resources :meals
  end


  root 'orders#index'
  # get 'users/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :user_orders
  has_many :users, through: :user_orders
  has_many :meals
  validates :restaurant_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :user_orders
    has_many :orders, through: :user_orders
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_filter :get_order

   # GET /orders/new
   def get_order
     @order= Order.find(params[:order_id])
   end
   def show
     @meal = @order.meals.find(params[:id])
   end

   def index
     @meals = @order.meals
   end
   def new

     @order = Order.new
   end

   def create
     @meal = @order.meals.new(params[:meal])
     respond_to do |format|
       if @meal.save
         format.html {redirect_to[@order, @meal]}
         format.json {render json:[@order,@meal],
                              status: :created,
                            location: [@order, @meal]}
        else
        render action: 'new'

      end

   end

   # POST /orders
   # POST /orders.json
#    def create
#  @meal = current_order.meals.build(meal_params)
#   # current_restaurant= Restaurant.find(params[:id])
#
#
# end
  # def new
  #   @meal= Meal.new
  #   # @meal= current_restaurant.meals.build
  #
  # end
  #
  # def create
  #   # @meal= current_restaurant.meals.build(meal_params)
  #   @meal= Meal.new(meal_params)
  #   if @meal.save
  #     redirect_to root_path, notice:"You successfully add meal"
  #   else
  #     render action: 'new'
  #   end
  # end

  private
  def meal_params
    params.require(:meal).permit(:dish_name, :price)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

 def index
   @orders = Order.all
   @order =Order.new
   @meal= Meal.new
  #  @orders = current_user.orders
  #   @meal = Meal.new
  #   @order= current_order
  #   respond_with(@meals)
  end
  def new
    @order = Order.new
  end
  def create
    @order = Order.new(order_params)
    @users = User.new
    if @order.save
      redirect_to root_path, notice:"Order was successfully created"
    else
      render action: 'new'
    end
  end

  def show
    @order = Order.find(params[:id])
  end


  def order_params
    params.require(:order).permit(:restaurant_name, :order_status, :dish_name, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SinglePageFoodBooking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Sing up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Log out",  destroy_user_session_path, :method => :delete %>
    <p class="notice"><%= notice %></p>


    <%= yield %>
  </body>
</html>

app/views/meals/new.html.erb
<%= form_for([@order, @meal) do |f| %>
<div class= "field">
<%= f.label :dish_name %>
<%= f.select :dish_name, ['fresh','old','rooting'] %>
</div>
<div class="field">
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div class= "actions" %>
<%= f.submit %>
</div>
<% end %>

app/views/orders/index.html.erb
<h1> orders list </h1>
<% @orders.each do |order| %>
<h2><%= order.restaurant_name %></h2>
<%= order.meals %>


<% end %>
<%= link_to "Add new restaurant", new_order_path %>
<%= link_to "Add new order", new_order_meal_path(@order) %>

app/views/orders/new.html.erb
<%= form_for(@order) do |f|  %>
<div class= "field">
<%= f.label :restaurant_name %>
<%= f.text_field :restaurant_name %>
</div>
<div class= "field">

  <%= f.select :order_status, ['completed', 'incompleted'] %>
</div>
<div class="actions">
<%= f.submit %>
</div>

<%end %>